{
 "title": "custom application",
 "description": "<description>",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center style=\"background-color:black;padding:1rem;\"><a href=\"http://www.cpacketnetworks.com\" target=\"_new\"><img width=\"220px\" src=\"/static/images/cpacket_white_text.svg\"></a></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "PCAP Download ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    { "title": "Download Packets", "type": "cclear-pcap-panel", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 } }
   ]
  },
  {
   "title": "custom application : Core servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "tcp_timeslice_summary_custom_application - \"bytes_server\" with  (\"server_custom_application\" =~ /^Core servers$/ Or \"client_custom_application\" =~ /^Core servers$/)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "repeat": "tcp_metric",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_server_custom_application,$tag_client_custom_application",
     "measurement": "flows_summary_vlan_tag_outer",
     "query": "SELECT sum(\"bytes_server\") FROM \"tcp_timeslice_summary_custom_application\" WHERE $timeFilter  AND (\"server_custom_application\" =~ /^Core servers$/ Or \"client_custom_application\" =~ /^Core servers$/) GROUP BY time($interval), \"server_custom_application\", \"client_custom_application\" fill(none)"
    }
   ]
  },
  {
   "title": "IP  (\"custom_application\" =~ /^Core servers$/ Or \"custom_application\" =~ /^Core servers$/)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "tcp_timeslice_summary_server_ip - \"bytes_server\" with  (\"custom_application\" =~ /^Core servers$/ Or \"custom_application\" =~ /^Core servers$/)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "repeat": "tcp_metric",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ip",
     "measurement": "flows_summary_vlan_tag_outer",
     "query": "SELECT sum(\"bytes_server\") FROM \"tcp_timeslice_summary_server_ip\" WHERE $timeFilter  AND (\"custom_application\" =~ /^Core servers$/ Or \"custom_application\" =~ /^Core servers$/) GROUP BY time($interval), \"ip\" fill(none)"
    }
   ]
  },
  {
   "title": "tcp_timeslice_summary_client_ip - \"bytes_server\" with  (\"custom_application\" =~ /^Core servers$/ Or \"custom_application\" =~ /^Core servers$/)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "repeat": "tcp_metric",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ip",
     "measurement": "flows_summary_vlan_tag_outer",
     "query": "SELECT sum(\"bytes_server\") FROM \"tcp_timeslice_summary_client_ip\" WHERE $timeFilter  AND (\"custom_application\" =~ /^Core servers$/ Or \"custom_application\" =~ /^Core servers$/) GROUP BY time($interval), \"ip\" fill(none)"
    }
   ]
  }
 ]
}